# Generated by Django 3.2.8 on 2021-10-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Employee Translation'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Organization Translation'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'verbose_name': 'Organization Type', 'verbose_name_plural': 'Organization Types'},
        ),
        migrations.AlterModelOptions(
            name='organizationtypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Organization Type Translation'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Reward', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AlterModelOptions(
            name='rewardfile',
            options={'verbose_name': 'Reward File', 'verbose_name_plural': 'Reward Files'},
        ),
        migrations.AlterModelOptions(
            name='rewardfiletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Reward File Translation'},
        ),
        migrations.AlterModelOptions(
            name='rewardtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Reward Translation'},
        ),
        migrations.AlterModelOptions(
            name='rewardtype',
            options={'verbose_name': 'Reward Type', 'verbose_name_plural': 'Reward Types'},
        ),
        migrations.AlterModelOptions(
            name='rewardtypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Reward Type Translation'},
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_of_issue',
            field=models.DateField(verbose_name='Date Of Issue'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.organization', verbose_name='Issued By'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.rewardtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='rewardfile',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='staff.reward', verbose_name='Reward'),
        ),
    ]
