# Generated by Django 3.2.8 on 2021-10-26 06:24

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211018_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(null=True, upload_to='reward_images/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.organizationtype', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.organization', verbose_name='Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationionality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nationality', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.position', verbose_name='Position'),
        ),
        migrations.CreateModel(
            name='PositionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Position')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='staff.position')),
            ],
            options={
                'verbose_name': 'position Translation',
                'db_table': 'staff_position_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NationalityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nation', models.CharField(max_length=30, verbose_name='Nationality')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='staff.nationality')),
            ],
            options={
                'verbose_name': 'nationality Translation',
                'db_table': 'staff_nationality_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
