# Generated by Django 3.2.8 on 2021-10-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20211026_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nationionality',
            new_name='nationality',
        ),
    ]
