# Generated by Django 3.2.8 on 2021-11-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_nationionality_employee_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Nationality', 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='nationalitytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Nationality Translation'},
        ),
    ]
