# Generated by Django 3.2.8 on 2021-11-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20211102_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='image',
        ),
        migrations.AddField(
            model_name='rewardtype',
            name='image',
            field=models.ImageField(null=True, upload_to='reward_images/', verbose_name='Image'),
        ),
    ]
