# Generated by Django 3.2.8 on 2021-11-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20211108_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='positiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Position Translation'},
        ),
    ]
