# Generated by Django 3.2.8 on 2021-11-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20211115_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='employeetranslation',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='employeetranslation',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='employeetranslation',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
